name: Cirrus CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  run-cirrus:
    name: Run Cirrus CI
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Cirrus CLI
        run: |
          curl -sL https://raw.githubusercontent.com/cirruslabs/cirrus-ci-cli/main/install.sh | bash -s -- --no-backup
          echo "$HOME/.cirrus/bin" >> $GITHUB_PATH

      - name: Set up Homebrew
        run: |
          # Install Homebrew if not already installed
          if ! command -v brew &> /dev/null; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
            eval "$(/opt/homebrew/bin/brew shellenv)"
          fi

      - name: Run Cirrus CI tasks
        run: |
          # Run the same tasks as defined in .cirrus.yml
          cirrus run --output=simple

  # Keep the existing lint job since it's lightweight and fast
  lint:
    name: Lint Shell Scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          check_together: 'yes'
          severity: error
