name: Test Dotfiles Setup

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [22.x]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install fnm
      run: |
        if [[ "${{ runner.os }}" == "macOS" ]]; then
          brew install fnm
        else
          curl -fsSL https://fnm.vercel.app/install | bash
          echo "$HOME/.local/share/fnm" >> $GITHUB_PATH
        fi
    
    - name: Setup Node.js
      run: |
        if [[ "${{ runner.os }}" == "macOS" ]]; then
          eval "$(fnm env)"
        else
          export PATH="$HOME/.local/share/fnm:$PATH"
          eval "$(fnm env)"
        fi
        fnm install ${{ matrix.node-version }}
        fnm use ${{ matrix.node-version }}
        node --version
        npm --version
    
    - name: Install dependencies
      run: npm install
    
    - name: Run tests
      run: npm test
    
    - name: Test bootstrap script
      run: |
        # Test that bootstrap script runs without errors
        ./bootstrap.sh
      env:
        CI: true
    
    - name: Test setup script (skip packages)
      run: npm run setup -- --skip-packages
      env:
        CI: true
    
    - name: Verify symlinks created
      run: |
        # Check that expected symlinks/files were created
        ls -la ~/.config/ || true
        ls -la ~/.zshrc || true
        ls -la ~/.tmux.conf || true
    
    - name: Test package installation (Ubuntu only)
      if: runner.os == 'Linux'
      run: |
        # Test that apt packages can be read and processed
        cat apt_packages.txt | grep -v '^#' | grep -v '^$' | head -5
        # Don't actually install packages in CI to save time
        echo "Package list verified"
    
    - name: Test package installation (macOS only)
      if: runner.os == 'macOS'
      run: |
        # Test that brew packages can be read and processed
        cat brew_packages.txt | grep -v '^#' | grep -v '^$' | head -5
        # Don't actually install packages in CI to save time
        echo "Package list verified"